### ISSUE TITLE
为后台跑团记录加入保存功能

### ISSUE THREAD

**Issue by FinZhang** [maliut/BotIM#1]
需求：开始录制后离开页面，返回时保留之前录制的文字。另设清除按钮清除记录

**Comment by maliut** [comment]
加个可选功能，不记录用户发出指令的那句话，这样应该可以显著减少记录内容，让记录更清晰

**Comment by maliut** [comment]
done. 
遗留问题：刷新后重新录制，若说话的两个人相同，也不会自动合并。小问题先不改了
